### ISSUE TITLE
this forked lab is missing html, images and video

### ISSUE THREAD

**Issue by Louiefigz** [learn-co-curriculum/html5-semantic-containers-code-along#1]
Hey so I forked this lab and opened it and it's blank so I had to copy and move files to make sure that this code was up to date before starting the video.  I posted this issue for another one of the exceptional realty labs but its also in this one as well.

**Comment by jongrover** [comment]
solved by https://github.com/learn-co-curriculum/html5-semantic-containers-code-along/pull/2
